### ISSUE TITLE
Quac! App - SubGHz actions cause the app to crash

### ISSUE THREAD

**Issue by asin9749** [Next-Flip/Momentum-Apps#11]
When you try to initiate any `sub-ghz` action:

1. the indicator LED flashes red
2. the app crashes
3. the flipper reboots showing the below

![IMG_2661](https://github.com/rdefeo/quac/assets/56191677/2e25ba56-f1ae-47fc-b8ae-6bdd380c256f)

CLI still functioning correctly, other Sub-GHz apps functioning correctly with the same files.

**Comment by WillyJL** [comment]
You're using a frequency blocked in your region most likely. Momentum > protocols > subghz bypass region lock. If not, provide more details.

**Comment by asin9749** [comment]
Region bypass is already activated on my end. The SubGHz was initially partially working using `Momentum Devbuild 392c31d` and `Quac! v.06`

I had created the folder structure required for my use case

![All_files](https://github.com/rdefeo/quac/assets/56191677/f45c916b-3ee5-4718-94e4-71f4d7baa085)

As you can see here there is a file `00_Doorbell.sub` which activates the doorbell for my house, which in turn activates the front porch and entrance lights. When I tried to emulate this I see the blue light flashing but it does not activate the doorbell. The original file works correctly with the Sub-GHz app. 

**Note all other Sub-GHz files I used were functioning correctly except for the "Doorbell"**

Contents of the file 00_Doorbell.sub are

`Filetype: Flipper SubGhz Key File`
`Version: 1`
`Frequency: 433920000`
`Preset: FuriHalSubGhzPresetOok650Async`
`Protocol: Holtek_HT12X`
`Bit: 12`
`Key: 00 00 00 00 00 00 05 71`
`TE: 325`

It seems to have clipped the last line from the original file below

`Filetype: Flipper SubGhz Key File`
`Version: 1`
`Frequency: 433920000`
`Preset: FuriHalSubGhzPresetOok650Async`
`Protocol: Holtek_HT12X`
`Bit: 12`
`Key: 00 00 00 00 00 00 05 71`
`TE: 325`
`Repeat: 200`

If I manually add `Repeat: 200` at the bottom of `00_Doorbell.sub` it removes itself once the QUAC app is loaded. It is noted that the lack of `repeat` is is likely a non-issue and was the reason for some of the May 6th  updates in the Quac code.

Flipper firmware at that time was `mntm-dev-9b3f7f49`, I had also tried `mntm-001` and `mntm-dev-b6d62b34` all give the same behaviour where this file will not run but the other Sub-GHz files I have `01_Garage.sub` for example ran fine.

I replayed both the `Quac` and `Original` versions of the file via the CLI. See screenshot below

![image](https://github.com/rdefeo/quac/assets/56191677/90ae37b9-5a33-47fe-a476-4f2d9431d663)

Both successfully triggered the bell as expected. Still not working when trying to trigger it from `Quac` though. I've tried adding it into one of the `Quac` subfolders or even moving its position in the list to test that as well but this also did not work (its old trauma from my early work days). The light flashes blue indicating its sending the signal but not sure if it is actually sending. 

That was the original issue I was encountering. Since rdefeo updated the code on the 6th May and pinged me to test the changes no Sub-GHz functionality has worked with any recent momentum dev or release build on my end. I am currently running `mntm-dev-02291d9d`

Is there a way for me to get some detailed logs for `Quac`? I am comfortable with coding in c just not comfortable with the flipper codebase (still learning), so happy to make minor changes, rebuild and test on my end to get this sorted.

Please let me know if this is not sufficient enough info or you need any additional info from me.

**Comment by asin9749** [comment]
From the trace log

417410 [I][AnimationManager] Unload animation 'PsyLaptop_128x64'
417417 [T][StorageApi] File/Dir 00003994 alloc
417421 [I][Loader] Loading /ext/apps/Tools/quac.fap
417425 [T][StorageApi] File 00003994 - 00005340 open (/ext/apps/Tools/quac.fap)
417501 [I][Loader] Mapping
417507 [I][Elf] Total size of loaded sections: 21021
417510 [T][StorageApi] File 00003994 - 00005340 closed
417513 [T][StorageApi] File/Dir 00003994 free
417515 [I][Loader] Loaded in 94ms
417517 [I][Loader] Starting app
417520 [I][Quac] QUAC! QUAC!
417523 [T][StorageApi] File/Dir 0000D0C8 alloc
417525 [I][Quac] SETTINGS: Reading: /data/.quac.conf
417535 [T][StorageApi] File 0000D0C8 - 0000D158 open (/data/.quac.conf)
417555 [T][StorageApi] File 0000D0C8 - 0000D158 closed
417558 [T][StorageApi] File/Dir 0000D0C8 free
417560 [I][Quac] Reading items from path: /data
417563 [T][StorageApi] File/Dir 0000D128 alloc
417567 [T][StorageApi] Dir 0000D128 - 0000D1C8 open (/data)
417588 [T][StorageApi] Dir 0000D128 - 0000D1C8 closed
417591 [T][StorageApi] File/Dir 0000D128 free
417593 [I][Quac] Generating scene: [depth=0] /data
426777 [I][Quac] Initiating item action: Doorbell
426780 [T][StorageApi] File/Dir 00014970 alloc
426784 [I][Quac] SUBGHZ: Action starting...
426787 [T][StorageApi] File/Dir 0000D1BC alloc
426793 [T][StorageApi] Dir 0000D1BC - 00014D8C open (/ext/apps_data/subghz/plugi                                                                                                                                                                                                                                 ns)
426798 [D][PluginManager] Loading /ext/apps_data/subghz/plugins/radio_device_cc1                                                                                                                                                                                                                                 101_ext.fal
426802 [T][StorageApi] File/Dir 00014D68 alloc
426809 [T][StorageApi] File 00014D68 - 00015074 open (/ext/apps_data/subghz/plug                                                                                                                                                                                                                                 ins/radio_device_cc1101_ext.fal)
426859 [I][Elf] Total size of loaded sections: 5224
426862 [T][StorageApi] File 00014D68 - 00015074 closed
426865 [T][StorageApi] File/Dir 00014D68 free
426868 [D][Fap] Library for subghz_radio_device, API v. 2 loaded
426871 [T][StorageApi] Dir 0000D1BC - 00014D8C closed
426874 [T][StorageApi] File/Dir 0000D1BC free
426877 [D][Fap] Library for subghz_radio_device, API v. 2 loaded
426880 [I][SubGhzDeviceRegistry] Loaded 2 radio device
426883 [I][SubGhzKeystore] Loading keystore /ext/subghz/assets/keeloq_mfcodes
426887 [T][StorageApi] File/Dir 00014E84 alloc
426894 [T][StorageApi] File 00014E84 - 00014E08 open (/ext/subghz/assets/keeloq_                                                                                                                                                                                                                                 mfcodes)
426949 [T][StorageApi] File 00014E84 - 00014E08 closed
426952 [T][StorageApi] File/Dir 00014E84 free
426954 [I][SubGhzKeystore] Loading keystore /ext/subghz/assets/keeloq_mfcodes_us                                                                                                                                                                                                                                 er
426958 [T][StorageApi] File/Dir 00014E14 alloc
426966 [T][StorageApi] File 00014E14 - 000150C4 open (/ext/subghz/assets/keeloq_                                                                                                                                                                                                                                 mfcodes_user)
426981 [T][StorageApi] File 00014E14 - 000150C4 closed
426984 [T][StorageApi] File/Dir 00014E14 free
426994 [T][StorageApi] File 00014970 - 00014E68 open (/data/01_Doorbell.sub)
427016 [D][FuriHalSubGhz] Loading custom preset
427018 [D][FuriHalSubGhz] Reg[0]: 02=0D
427020 [D][FuriHalSubGhz] Reg[2]: 03=07
427022 [D][FuriHalSubGhz] Reg[4]: 08=32
427025 [D][FuriHalSubGhz] Reg[6]: 0B=06
427027 [D][FuriHalSubGhz] Reg[8]: 14=00
427029 [D][FuriHalSubGhz] Reg[10]: 13=00
427032 [D][FuriHalSubGhz] Reg[12]: 12=30
427034 [D][FuriHalSubGhz] Reg[14]: 11=32
427036 [D][FuriHalSubGhz] Reg[16]: 10=17
427038 [D][FuriHalSubGhz] Reg[18]: 18=18
427041 [D][FuriHalSubGhz] Reg[20]: 19=18
427043 [D][FuriHalSubGhz] Reg[22]: 1D=91
427045 [D][FuriHalSubGhz] Reg[24]: 1C=00
427048 [D][FuriHalSubGhz] Reg[26]: 1B=07
427050 [D][FuriHalSubGhz] Reg[28]: 20=FB
427052 [D][FuriHalSubGhz] Reg[30]: 22=11
427055 [D][FuriHalSubGhz] Reg[32]: 21=B6
427057 [D][FuriHalSubGhz] PA[34]:  00
427059 [D][FuriHalSubGhz] PA[35]:  00
427061 [D][FuriHalSubGhz] PA[36]:  00
427063 [D][FuriHalSubGhz] PA[37]:  C0
427066 [D][FuriHalSubGhz] PA[38]:  00
427068 [D][FuriHalSubGhz] PA[39]:  00
427070 [D][FuriHalSubGhz] PA[40]:  00
427072 [D][FuriHalSubGhz] PA[41]:  00
427074 [D][FuriHalSubGhz] PA[42]:  00
427076 [D][FuriHalSubGhz] PA[43]:  00
427081 [I][Quac] Protocol != RAW
427090 [E][Quac] Error transmitter

**Comment by WillyJL** [comment]
found the issue, repeat is being added weirdly and polluting the protocol name. then, this causes tre transmitter to not be allocated, and while trying to fail gracefully it tries to free this transmitter that was never allocated
![image](https://github.com/Next-Flip/Momentum-Apps/assets/49810075/df3ceebb-3796-446e-b7f9-3e731c550227)

**Comment by WillyJL** [comment]
fixed in mntm-004

**Comment by asin9749** [comment]
Thanks so much, it's no longer crashing out and you have given me enough info that I can attempt fix the rest of the broken subghz action

**Comment by WillyJL** [comment]
Should be working as intended now

**Comment by asin9749** [comment]
Sadly for me no still erroring out. It's no longer crashing completely (so you've solved the issue :) ) but its still not actually transmitting any SubGHz actions for me.

387964 [I][Loader] Loading /ext/apps/Tools/quac.fap
387968 [T][StorageApi] File 0000F3F4 - 000052D0 open (/ext/apps/Tools/quac.fap)
388040 [I][Loader] Mapping
388045 [I][Elf] Total size of loaded sections: 20965
388048 [T][StorageApi] File 0000F3F4 - 000052D0 closed
388051 [T][StorageApi] File/Dir 0000F3F4 free
388054 [I][Loader] Loaded in 90ms
388056 [I][Loader] Starting app
388058 [I][Quac] QUAC! QUAC!
388061 [T][StorageApi] File/Dir 0000ED78 alloc
388063 [I][Quac] SETTINGS: Reading: /data/.quac.conf
388073 [T][StorageApi] File 0000ED78 - 0000EE08 open (/data/.quac.conf)
388093 [T][StorageApi] File 0000ED78 - 0000EE08 closed
388096 [T][StorageApi] File/Dir 0000ED78 free
388098 [I][Quac] Reading items from path: /data
388101 [T][StorageApi] File/Dir 0000EDD8 alloc
388105 [T][StorageApi] Dir 0000EDD8 - 0001F360 open (/data)
388140 [T][StorageApi] Dir 0000EDD8 - 0001F360 closed
388143 [T][StorageApi] File/Dir 0000EDD8 free
388145 [I][Quac] Generating scene: [depth=0] /data
390509 [I][Quac] Initiating item action: Doorbell
390512 [T][StorageApi] File/Dir 0001F550 alloc
390516 [I][Quac] SUBGHZ: Action starting...
390519 [T][StorageApi] File/Dir 0000EE4C alloc
390525 [T][StorageApi] Dir 0000EE4C - 00010AA8 open (/ext/apps_data/subghz/plugins)
390530 [D][PluginManager] Loading /ext/apps_data/subghz/plugins/radio_device_cc1101_ext.fal
390534 [T][StorageApi] File/Dir 00010A84 alloc
390540 [T][StorageApi] File 00010A84 - 0000F9D4 open (/ext/apps_data/subghz/plugins/radio_device_cc1101_ext.fal)
390588 [I][Elf] Total size of loaded sections: 5224
390591 [T][StorageApi] File 00010A84 - 0000F9D4 closed
390594 [T][StorageApi] File/Dir 00010A84 free
390596 [D][Fap] Library for subghz_radio_device, API v. 2 loaded
390600 [T][StorageApi] Dir 0000EE4C - 00010AA8 closed
390603 [T][StorageApi] File/Dir 0000EE4C free
390605 [D][Fap] Library for subghz_radio_device, API v. 2 loaded
390609 [I][SubGhzDeviceRegistry] Loaded 2 radio device
390611 [I][SubGhzKeystore] Loading keystore /ext/subghz/assets/keeloq_mfcodes
390615 [T][StorageApi] File/Dir 00010AA4 alloc
390623 [T][StorageApi] File 00010AA4 - 00010B24 open (/ext/subghz/assets/keeloq_mfcodes)
390678 [T][StorageApi] File 00010AA4 - 00010B24 closed
390680 [T][StorageApi] File/Dir 00010AA4 free
390683 [I][SubGhzKeystore] Loading keystore /ext/subghz/assets/keeloq_mfcodes_user
390687 [T][StorageApi] File/Dir 0000DA68 alloc
390695 [T][StorageApi] File 0000DA68 - 00010B34 open (/ext/subghz/assets/keeloq_mfcodes_user)
390710 [T][StorageApi] File 0000DA68 - 00010B34 closed
390712 [T][StorageApi] File/Dir 0000DA68 free
390728 [T][StorageApi] File 0001F550 - 0000DA94 open (/data/01_Doorbell.sub)
390742 [D][FuriHalSubGhz] Loading custom preset
390745 [D][FuriHalSubGhz] Reg[0]: 02=0D
390747 [D][FuriHalSubGhz] Reg[2]: 03=07
390749 [D][FuriHalSubGhz] Reg[4]: 08=32
390752 [D][FuriHalSubGhz] Reg[6]: 0B=06
390754 [D][FuriHalSubGhz] Reg[8]: 14=00
390756 [D][FuriHalSubGhz] Reg[10]: 13=00
390758 [D][FuriHalSubGhz] Reg[12]: 12=30
390761 [D][FuriHalSubGhz] Reg[14]: 11=32
390763 [D][FuriHalSubGhz] Reg[16]: 10=17
390765 [D][FuriHalSubGhz] Reg[18]: 18=18
390768 [D][FuriHalSubGhz] Reg[20]: 19=18
390770 [D][FuriHalSubGhz] Reg[22]: 1D=91
390772 [D][FuriHalSubGhz] Reg[24]: 1C=00
390774 [D][FuriHalSubGhz] Reg[26]: 1B=07
390777 [D][FuriHalSubGhz] Reg[28]: 20=FB
390779 [D][FuriHalSubGhz] Reg[30]: 22=11
390781 [D][FuriHalSubGhz] Reg[32]: 21=B6
390784 [D][FuriHalSubGhz] PA[34]: 00
390786 [D][FuriHalSubGhz] PA[35]: 00
390788 [D][FuriHalSubGhz] PA[36]: 00
390790 [D][FuriHalSubGhz] PA[37]: C0
390792 [D][FuriHalSubGhz] PA[38]: 00
390795 [D][FuriHalSubGhz] PA[39]: 00
390797 [D][FuriHalSubGhz] PA[40]: 00
390799 [D][FuriHalSubGhz] PA[41]: 00
390801 [D][FuriHalSubGhz] PA[42]: 00
390803 [D][FuriHalSubGhz] PA[43]: 00
390808 [I][Quac] Protocol != RAW
390823 [T][StorageApi] File/Dir 0000EE4C alloc
390838 [T][StorageApi] File 0000EE4C - 0001D920 open (/any/.scratch.pad)
390859 [T][StorageApi] File 0000EE4C - 0001D920 closed
390861 [T][StorageApi] File/Dir 0000EE4C free
390870 [E][Quac] Error transmitter
390876 [T][StorageApi] File 0001F550 - 0000DA94 closed
390878 [T][StorageApi] File/Dir 0001F550 free
390881 [I][Quac] SUBGHZ: Action complete.
392912 [I][Dolphin] Flush stats
392913 [I][SavedStruct] Saving "/ext/.config/dolphin.state"
392919 [T][StorageApi] File/Dir 0001F35C alloc
392936 [T][StorageApi] File 0001F35C - 0000EE3C open (/ext/.config/dolphin.state)
392946 [T][StorageApi] File 0001F35C - 0000EE3C closed
392949 [T][StorageApi] File/Dir 0001F35C free
392951 [I][DolphinState] State saved
406630 [I][Quac] Initiating item action: Garage
406634 [T][StorageApi] File/Dir 0001F550 alloc
406638 [I][Quac] SUBGHZ: Action starting...
406640 [T][StorageApi] File/Dir 0000EE4C alloc
406648 [T][StorageApi] Dir 0000EE4C - 00010AA8 open (/ext/apps_data/subghz/plugins)
406653 [D][PluginManager] Loading /ext/apps_data/subghz/plugins/radio_device_cc1101_ext.fal
406657 [T][StorageApi] File/Dir 00010A84 alloc
406661 [T][StorageApi] File 00010A84 - 0000F9D4 open (/ext/apps_data/subghz/plugins/radio_device_cc1101_ext.fal)
406711 [I][Elf] Total size of loaded sections: 5224
406714 [T][StorageApi] File 00010A84 - 0000F9D4 closed
406717 [T][StorageApi] File/Dir 00010A84 free
406719 [D][Fap] Library for subghz_radio_device, API v. 2 loaded
406723 [T][StorageApi] Dir 0000EE4C - 00010AA8 closed
406726 [T][StorageApi] File/Dir 0000EE4C free
406728 [D][Fap] Library for subghz_radio_device, API v. 2 loaded
406731 [I][SubGhzDeviceRegistry] Loaded 2 radio device
406734 [I][SubGhzKeystore] Loading keystore /ext/subghz/assets/keeloq_mfcodes
406738 [T][StorageApi] File/Dir 00010AA4 alloc
406748 [T][StorageApi] File 00010AA4 - 00010B24 open (/ext/subghz/assets/keeloq_mfcodes)
406821 [T][StorageApi] File 00010AA4 - 00010B24 closed
406824 [T][StorageApi] File/Dir 00010AA4 free
406826 [I][SubGhzKeystore] Loading keystore /ext/subghz/assets/keeloq_mfcodes_user
406830 [T][StorageApi] File/Dir 0000DA68 alloc
406838 [T][StorageApi] File 0000DA68 - 00010B34 open (/ext/subghz/assets/keeloq_mfcodes_user)
406853 [T][StorageApi] File 0000DA68 - 00010B34 closed
406856 [T][StorageApi] File/Dir 0000DA68 free
406866 [T][StorageApi] File 0001F550 - 00010B34 open (/data/02_Garage.sub)
406877 [D][FuriHalSubGhz] Loading custom preset
406879 [D][FuriHalSubGhz] Reg[0]: 02=REDACTED
406882 [D][FuriHalSubGhz] Reg[2]: 03=REDACTED
406884 [D][FuriHalSubGhz] Reg[4]: 08=REDACTED
406886 [D][FuriHalSubGhz] Reg[6]: 0B=REDACTED
406888 [D][FuriHalSubGhz] Reg[8]: 14=REDACTED
406891 [D][FuriHalSubGhz] Reg[10]: 13=REDACTED
406893 [D][FuriHalSubGhz] Reg[12]: 12=REDACTED
406895 [D][FuriHalSubGhz] Reg[14]: 11=REDACTED
406898 [D][FuriHalSubGhz] Reg[16]: 10=REDACTED
406900 [D][FuriHalSubGhz] Reg[18]: 18=REDACTED
406902 [D][FuriHalSubGhz] Reg[20]: 19=REDACTED
406904 [D][FuriHalSubGhz] Reg[22]: 1D=REDACTED
406907 [D][FuriHalSubGhz] Reg[24]: 1C=REDACTED
406909 [D][FuriHalSubGhz] Reg[26]: 1B=REDACTED
406911 [D][FuriHalSubGhz] Reg[28]: 20=REDACTED
406914 [D][FuriHalSubGhz] Reg[30]: 22=REDACTED
406916 [D][FuriHalSubGhz] Reg[32]: 21=REDACTED
406918 [D][FuriHalSubGhz] PA[34]: REDACTED
406920 [D][FuriHalSubGhz] PA[35]: REDACTED
406923 [D][FuriHalSubGhz] PA[36]: REDACTED
406925 [D][FuriHalSubGhz] PA[37]: REDACTED
406927 [D][FuriHalSubGhz] PA[38]: REDACTED
406929 [D][FuriHalSubGhz] PA[39]: REDACTED
406931 [D][FuriHalSubGhz] PA[40]: REDACTED
406933 [D][FuriHalSubGhz] PA[41]: REDACTED
406936 [D][FuriHalSubGhz] PA[42]: REDACTED
406938 [D][FuriHalSubGhz] PA[43]: REDACTED
406942 [I][Quac] Protocol != RAW
406951 [E][Quac] Error transmitter
406958 [T][StorageApi] File 0001F550 - 00010B34 closed
406960 [T][StorageApi] File/Dir 0001F550 free

I will attempt a look at it in a few weeks once I have some more free time.

**Comment by WillyJL** [comment]
@asin9749 you need to delete and import the file again. the previous issues with the subghz actions have clobbered the protocol name in the file itself, that file is not usable anymore.

**Comment by asin9749** [comment]
That's rather embarrassing on my part, all good now. Thanks again, for the quick work and your patience with me. I owe you one, please feel free to call it in when you need 👍🏽
